---
title: "plotting_adv"
author: "Lincoln"
date: "5/20/2019"
output: html_document
---

```{r}
library(ggplot2)
library(reshape2)
```

```{r}
setwd('/Users/lincoln.harris/code/ercc_exploration/')
```

read in
```{r}
sub_rates_TN <- read.csv('sub_rates_TN.csv', header = FALSE)
sub_rates_PER <- read.csv('sub_rates_PER.csv', header = FALSE)
sub_rates_PD <- read.csv('sub_rates_PD.csv', header = FALSE)
```

```{r}
sub_rates_TN$group <- 'TN'
sub_rates_PER$group <- 'PER'
sub_rates_PD$group <- 'PD'
```

combine
```{r}
big_df <- rbind(sub_rates_PD, sub_rates_PER, sub_rates_TN)
```

basic plot
```{r}
p0 <- ggplot(big_df, aes(x=group, y=V1, fill=group)) + geom_boxplot() 
p0
```

log scale
```{r}
p1 <- ggplot(big_df, aes(x=group, y=V1)) + geom_boxplot() + scale_y_log10()
p1
```

remove outliers, then plot
```{r}
# compute lower and upper whiskers
ylim1 = boxplot.stats(big_df$V1)$stats[c(1, 5)]

# scale y limits based on ylim1
p1 = p0 + coord_cartesian(ylim = ylim1*1.05)
p1 + labs(x='treatment status', y='base substitution rate') 
```

add in points
```{r}
p1 + labs(x='treatment status', y='base substitution rate') +
  geom_point(position = 'jitter', alpha = 1/10)
```

can i fix the ordering here? 
```{r}
big_df$group <- factor(big_df$group,
    levels = c('TN','PER','PD'),ordered = TRUE)
```

yes!
```{r}
p2 <- ggplot(big_df, aes(x=group, y=V1, fill=group)) + geom_boxplot() 
p3 = p2 + coord_cartesian(ylim = ylim1*1.05)
p3 + labs(x='treatment status', y='base substitution rate') 
```

```{r}
pdf('ercc_distro_noOutliers.pdf', width = 10, height = 10)
p3 + labs(x='treatment status', y='base substitution rate') 
dev.off()
```

can i add sig tests?

```{r}
#install.packages('ggpubr')
library(ggpubr)
```

```{r}
my_comparisons = list( c("TN", "PER"), c("PER", "PD"), c("TN", "PD") )

#ggboxplot(ToothGrowth, x = "dose", y = "len",
#          color = "dose", palette = "jco")+ 
#  stat_compare_means(comparisons = my_comparisons, label.y = c(29, 35, 40))+
#  stat_compare_means(label.y = 45)

p3 + labs(x='treatment status', y='base substitution rate') +
  stat_compare_means(comparisons = my_comparisons, label = 'p.format', method = "t.test")
```

```{r}
test <- pairwise.wilcox.test(x = big_df$V1, g = big_df$group)
test <- as.data.frame(test$p.value)
```

```{r}
p3 + ggsignif::geom_signif(comparisons = list(c("PD", "PER")), map_signif_level=TRUE, annotations = '0.002063192') + 
  ggsignif::geom_signif(comparisons = list(c("PD", "TN")), map_signif_level=TRUE, annotations = '5.940442e-23') + 
  ggsignif::geom_signif(comparisons = list(c("PER", "TN")), map_signif_level=TRUE, annotations = '2.063192e-03')
```

